esf_espace_abonne_homepage:
    path:     /
    defaults: { _controller: ESFEspaceAbonneBundle:Back:index }

esf_espace_abonne_monProfil:
    path:      /back/monprofil/
    defaults: { _controller: ESFEspaceAbonneBundle:Back:monprofil }

esf_espace_abonne_mesParametres:
    path:      /back/mesparametres
    defaults: { _controller: ESFEspaceAbonneBundle:Back:mesparametres }
esf_espace_abonne_mesParametresMDP:
    path:      /back/mesparametresMDP
    defaults: { _controller: ESFEspaceAbonneBundle:Back:mesparametresMDP }
esf_espace_abonne_mesParametresMAIL:
    path:      /back/mesparametresMAIL
    defaults: { _controller: ESFEspaceAbonneBundle:Back:mesparametresMAIL }

esf_espace_abonne_mesDemandes:
    path:      /back/mesdemandes
    defaults: { _controller: ESFEspaceAbonneBundle:Back:mesdemandes }
esf_espace_abonne_detailsDemandes:
    path:      /back/detailsdemandes/{id}
    defaults: { _controller: ESFEspaceAbonneBundle:Back:detailsdemandes }
esf_espace_abonne_modifierDemandes:
    path:      /back/modifierdemandes/{id}
    defaults: { _controller: ESFEspaceAbonneBundle:Back:modifierdemandes }
    methods: GET|POST

esf_espace_abonne_mesDocuments:
    path:      /back/mesdocuments
    defaults: { _controller: ESFEspaceAbonneBundle:Back:mesdocuments }
esf_espace_abonne_aide:
    path:      /back/aide
    defaults: { _controller: ESFEspaceAbonneBundle:Back:aide } 
esf_espace_abonne_contact:
    path:      /back/contact
    defaults: { _controller: ESFEspaceAbonneBundle:Back:contact }
    methods: POST|GET 

esf_espace_abonne_universiteStepsOne:
    path:      /back/universiteOne
    defaults: { _controller: ESFEspaceAbonneBundle:Back:universiteOne } 
esf_espace_abonne_universiteStepsTwo:
    path:      /back/universiteTwo/{id}
    defaults: { _controller: ESFEspaceAbonneBundle:Back:universiteTwo } 
esf_espace_abonne_universiteStepsThree:
    path:      /back/universiteThree/{id}
    defaults: { _controller: ESFEspaceAbonneBundle:Back:universiteTwo } 

esf_espace_abonne_langueStepsOne:
    path:      /back/langueOne
    defaults: { _controller: ESFEspaceAbonneBundle:Back:langueOne } 
esf_espace_abonne_langueStepsTwo:
    path:      /back/langueTwo
    defaults: { _controller: ESFEspaceAbonneBundle:Back:langueTwo } 
esf_espace_abonne_langueStepsThree:
    path:      /back/langueThree
    defaults: { _controller: ESFEspaceAbonneBundle:Back:langueTwo } 

esf_espace_abonne_logementStepsOne:
    path:      /back/logementOne
    defaults: { _controller: ESFEspaceAbonneBundle:Back:logementOne }    
esf_espace_abonne_logementStepsTwo:
    path:      /back/logementTwo
    defaults: { _controller: ESFEspaceAbonneBundle:Back:logementTwo } 
esf_espace_abonne_logementStepsThree:
    path:      /back/logementThree
    defaults: { _controller: ESFEspaceAbonneBundle:Back:logementTwo } 

esf_espace_abonne_preparationStepsOne:
    path:      /back/preparationOne
    defaults: { _controller: ESFEspaceAbonneBundle:Back:preparationOne }    
esf_espace_abonne_preparationStepsTwo:
    path:      /back/preparationTwo
    defaults: { _controller: ESFEspaceAbonneBundle:Back:preparationTwo } 
esf_espace_abonne_preparationStepsThree:
    path:      /back/preparationThree
    defaults: { _controller: ESFEspaceAbonneBundle:Back:preparationTwo } 

esf_espace_abonne_mutuelle:
    path:      /back/mutuelle
    defaults: { _controller: ESFEspaceAbonneBundle:Back:mutuelle }       

