<?php

namespace Proxies\__CG__\ESF\EspaceAbonneBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EA_Document_Inscription extends \ESF\EspaceAbonneBundle\Entity\EA_Document_Inscription implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Document_Inscription' . "\0" . 'id', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Document_Inscription' . "\0" . 'nom', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Document_Inscription' . "\0" . 'pdfFile', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Document_Inscription' . "\0" . 'pdfName', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Document_Inscription' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Document_Inscription' . "\0" . 'id', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Document_Inscription' . "\0" . 'nom', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Document_Inscription' . "\0" . 'pdfFile', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Document_Inscription' . "\0" . 'pdfName', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Document_Inscription' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EA_Document_Inscription $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlt($alt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlt', [$alt]);

        return parent::setAlt($alt);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlt', []);

        return parent::getAlt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhysique(\ESF\EspaceAbonneBundle\Entity\EA_Physique $physique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhysique', [$physique]);

        return parent::setPhysique($physique);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhysique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhysique', []);

        return parent::getPhysique();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdfName($pdfName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdfName', [$pdfName]);

        return parent::setPdfName($pdfName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdfName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfName', []);

        return parent::getPdfName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setpdfFile(\Symfony\Component\HttpFoundation\File\File $pdf = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setpdfFile', [$pdf]);

        return parent::setpdfFile($pdf);
    }

    /**
     * {@inheritDoc}
     */
    public function getpdfFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getpdfFile', []);

        return parent::getpdfFile();
    }

}
