<?php

namespace Proxies\__CG__\ESF\EspaceAbonneBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EA_Morale extends \ESF\EspaceAbonneBundle\Entity\EA_Morale implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'personne', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'langues', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'id', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'raisonsocial', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'siret', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'fax', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'naf', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'url', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'alt'];
        }

        return ['__isInitialized__', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'personne', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'langues', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'id', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'raisonsocial', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'siret', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'fax', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'naf', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'url', '' . "\0" . 'ESF\\EspaceAbonneBundle\\Entity\\EA_Morale' . "\0" . 'alt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EA_Morale $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonsocial($raisonsocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonsocial', [$raisonsocial]);

        return parent::setRaisonsocial($raisonsocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonsocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonsocial', []);

        return parent::getRaisonsocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiret($siret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiret', [$siret]);

        return parent::setSiret($siret);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiret', []);

        return parent::getSiret();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaf($naf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaf', [$naf]);

        return parent::setNaf($naf);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaf', []);

        return parent::getNaf();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', [$url]);

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', []);

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlt($alt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlt', [$alt]);

        return parent::setAlt($alt);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlt', []);

        return parent::getAlt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonne(\ESF\EspaceAbonneBundle\Entity\EA_Personne $personne = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonne', [$personne]);

        return parent::setPersonne($personne);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonne', []);

        return parent::getPersonne();
    }

    /**
     * {@inheritDoc}
     */
    public function addLangue(\ESF\EspaceAbonneBundle\Entity\EA_Langue $langue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLangue', [$langue]);

        return parent::addLangue($langue);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLangue(\ESF\EspaceAbonneBundle\Entity\EA_Langue $langue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLangue', [$langue]);

        return parent::removeLangue($langue);
    }

    /**
     * {@inheritDoc}
     */
    public function getLangues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLangues', []);

        return parent::getLangues();
    }

}
