<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * EA_Document_InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EA_Document_InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
