<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * EA_Demande_InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EA_Demande_InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDemandesIncriptions($idphysique)
	{
		$qb = $this
		->createQueryBuilder('u')
		->leftJoin('u.documentinscription', 'doc')
		->where('u.physique = :id')
		->setParameter('id', $idphysique)		
		;

		return $qb->getQuery()->getResult();
	}
}
