<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * EA_DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EA_DocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
