<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * EA_Formation_MoraleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EA_Formation_MoraleRepository extends \Doctrine\ORM\EntityRepository
{
}
