<?php

namespace ESF\EspaceAbonneBundle\Repository;

use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * EA_ImageRepository
 * @Vich\Uploadable
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EA_ImageRepository extends \Doctrine\ORM\EntityRepository
{
}
