<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * EA_MoraleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EA_MoraleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getMutuel($name)
	{
		$qb = $this
		->createQueryBuilder('u')
		->where('u.raisonsocial = :nom')
		->setParameter('nom', $name)
		;

		return $qb->getQuery()->getResult();
	}
}
