<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * EA_Type_InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EA_Type_InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
