<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * T_Document_UniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Document_UniversiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDocumentIncription($universiteId)
	{
		$qb = $this
		->createQueryBuilder('u')
		->where('u.universite = :id')
		->setParameter('id', $universiteId)		
		;

		return $qb->getQuery()->getResult();

	}
}
