<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * T_Document_PartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Document_PartenaireRepository extends \Doctrine\ORM\EntityRepository
{

	public function getDocumentIncription($partenaireId)
	{
		$qb = $this
		->createQueryBuilder('u')
		->where('u.partenaire = :id')
		->setParameter('id', $partenaireId)		
		;

		return $qb->getQuery()->getResult();

	}
}

