<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * T_Formation_UniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Formation_UniversiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getFormation() {

		$qb = $this
		->createQueryBuilder('u')
		->orderBy('u.formation', 'ASC')
		;

		return $qb->getQuery()->getResult();
	}

}
