<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * T_Image_UniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Image_UniversiteRepository extends \Doctrine\ORM\EntityRepository
{

}
