<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * T_Langue_UniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Langue_UniversiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLangue($idFormation) {

		$qb = $this
		->createQueryBuilder('u')
		->where('u.id = :idFormation')
		->setParameter('idFormation', $idFormation)
		->orderBy('u.langue', 'ASC')
		;

		return $qb;
	}
}
