<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * T_Langue_Formation_PartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Langue_Formation_PartenaireRepository extends \Doctrine\ORM\EntityRepository
{
}
