<?php

namespace ESF\EspaceAbonneBundle\Repository;

/**
 * T_Pays_UniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class T_Pays_UniversiteRepository extends \Doctrine\ORM\EntityRepository
{
}
